name: 'Hello'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
    - run: ${{ github.action_path }}/hello.sh
      shell: bash
    - name: Push slipstream metadata image
      uses: BrandwatchLtd/slipstream-actions/push-image@main
      id: push-to-slipstream
      with:
        service: setupstore-api
        labels: project=analytics
        dockerRegistry: eu.gcr.io/bw-prod-analytics0
